// <auto-generated />
namespace hailinh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_pricelangding_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_pricelangding_image));
        
        string IMigrationMetadata.Id
        {
            get { return "202609150541457_add_pricelangding_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
