// <auto-generated />
namespace namanh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_home_config_titles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_home_config_titles));
        
        string IMigrationMetadata.Id
        {
            get { return "202609070855449_add_home_config_titles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
