// <auto-generated />
namespace namanh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addtableprice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtableprice));
        
        string IMigrationMetadata.Id
        {
            get { return "202605100352323_add-table-price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
