// <auto-generated />
namespace namanh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addlocationpricefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlocationpricefields));

        string IMigrationMetadata.Id
        {
            get { return "202606141500000_add-location-price-fields"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
